<?php
/**
 * @file
 * Install file for the abn module.
 */

/**
 * Implements hook_field_schema().
 */
function abn_field_schema($field) {
  $columns = array(
      'abn' => array(
        'type' => 'varchar',
        'length' => 16, // ABN has max length of 11 but whitespace is allowed.
        'not null' => FALSE,
        'sortable' => TRUE,
      ),
    );

  $indexes = array(
    'abn' => array('abn'),
  );
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}
